window.PEDIDOS_CLIENTS = {
  rivadavia: {
    key: "rivadavia",
    name: "Rivadavia",
    sheetId: "1gOnrFRnQuEq6GnfpzA9XcIUZkE35z5sq5ENP38tRMho",
    sheetGid: "0",
    logoPath: "Logo.png",
    ui: {
      title: "Pedidos Rivadavia",
      searchPlaceholder: "Buscar familias o productos...",
      sendButtonLabel: "Copiar Pedido y Abrir WhatsApp",
      detailTitle: "Detalle del pedido",
    },
    thicknessMeta: {
      "3": { id: "3", label: "3 mm", summaryLabel: "3mm", messageLabel: "3mm", icon: "view_week" },
      "15": { id: "15", label: "15 mm", summaryLabel: "15mm", messageLabel: "15mm", icon: "splitscreen" },
    },
  },
  moreira: {
    key: "moreira",
    name: "Moreira",
    sheetId: "1rz_fOaMzuThxT-C9g9pv2AicV2wmTUo4lzUhI0xgaFw",
    sheetGid: "0",
    catalogMode: "price-list",
    summaryMode: "value",
    ui: {
      title: "Pedidos Moreira",
      searchPlaceholder: "Buscar productos...",
      sendButtonLabel: "Copiar Pedido y Abrir WhatsApp",
      detailTitle: "Detalle del pedido",
    },
    thicknessMeta: {
      letras: {
        id: "letras",
        label: "Letras",
        summaryLabel: "Letras",
        messageLabel: "Letras",
        summaryUnit: "letras",
        icon: "title",
        type: "letters",
      },
    },
    lettersConfig: {
      materialLabel: "MDF 5 mm",
      sizes: ["22", "27", "33"],
      priceRowLabel: "$ Unit",
      taxRate: 0.21,
      quickSteps: [1, 10, 50],
      filters: [
        { id: "letters", label: "Letras", mode: "letters" },
        { id: "numbers", label: "Números", mode: "numbers" },
      ],
      letters: [
        "A",
        "B",
        "C",
        "D",
        "E",
        "F",
        "G",
        "H",
        "I",
        "J",
        "K",
        "L",
        "M",
        "N",
        "\u00d1",
        "O",
        "P",
        "Q",
        "R",
        "S",
        "T",
        "U",
        "V",
        "W",
        "X",
        "Y",
        "Z",
        "0",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
      ],
    },
  },
};
