window.PEDIDOS_CLIENTS = {
  rivadavia: {
    key: "rivadavia",
    name: "Rivadavia",
    sheetId: "1tD0qUBePV0-UPSKwXmf9fNDHEO8u4dOtfDyvKerxVvc",
    sheetGid: "797684977",
    logoPath: "Logo.png",
    ui: {
      title: "Pedidos Rivadavia",
      searchPlaceholder: "Buscar familias o productos...",
      sendButtonLabel: "Enviar por WhatsApp y Mail",
      detailTitle: "Detalle del pedido",
    },
    sendMode: "form-post-email",
    emailTo: "mymfibrofacil.web@gmail.com",
    sendEndpoint: "https://script.google.com/macros/s/AKfycbwlEwt2SvBLacxP1hTl8RhjgBOCuo_aebePiPXA8RdcLOpZfgLFaFOTq0GxIjaO-RJxig/exec",
    sendXubioOrder: true,
    xubio: {
      clienteId: 7756831,
      mode: "rivadavia-corte-placa",
      listaPrecioId: 10194,
      productoPorEspesor: {
        "3": 2465942,
        "15": 2465943,
      },
    },
    thicknessMeta: {
      "3": { id: "3", label: "3 mm", summaryLabel: "3mm", messageLabel: "3mm", icon: "view_week" },
      "15": { id: "15", label: "15 mm", summaryLabel: "15mm", messageLabel: "15mm", icon: "splitscreen" },
    },
  },
  moreira: {
    key: "moreira",
    name: "Moreira",
    sheetId: "1tD0qUBePV0-UPSKwXmf9fNDHEO8u4dOtfDyvKerxVvc",
    sheetGid: "0",
    catalogSheetGid: "0",
    catalogMode: "moreira-shared-price-list",
    summaryMode: "value",
    sendMode: "form-post-email",
    emailTo: "mymfibrofacil@gmail.com,mymfibrofacil.web@gmail.com",
    emailSubjectPrefix: "Moreira",
    sendEndpoint: "https://script.google.com/macros/s/AKfycbwlEwt2SvBLacxP1hTl8RhjgBOCuo_aebePiPXA8RdcLOpZfgLFaFOTq0GxIjaO-RJxig/exec",
    ui: {
      title: "Pedidos Moreira",
      searchPlaceholder: "Buscar productos...",
      sendButtonLabel: "Enviar Pedido por Mail",
      detailTitle: "Detalle del pedido",
    },
    thicknessMeta: {
      kits: {
        id: "kits",
        label: "Kits",
        summaryLabel: "Kits",
        messageLabel: "Kits",
        summaryUnit: "items",
        icon: "deployed_code",
        type: "kits",
      },
      individuales: {
        id: "individuales",
        label: "Individuales",
        summaryLabel: "Individuales",
        messageLabel: "Individuales",
        summaryUnit: "items",
        icon: "inventory_2",
        type: "price-list",
      },
      letras: {
        id: "letras",
        label: "Letras",
        summaryLabel: "Letras",
        messageLabel: "Letras",
        summaryUnit: "letras",
        icon: "title",
        type: "letters",
      },
    },
    lettersConfig: {
      materialLabel: "MDF 5 mm",
      sizes: ["22", "27", "33"],
      priceRowLabel: "$ Unit",
      taxRate: 0.21,
      quickSteps: [1, 10, 50],
      filters: [
        { id: "letters", label: "Letras", mode: "letters" },
        { id: "numbers", label: "Números", mode: "numbers" },
      ],
      letters: [
        "A",
        "B",
        "C",
        "D",
        "E",
        "F",
        "G",
        "H",
        "I",
        "J",
        "K",
        "L",
        "M",
        "N",
        "\u00d1",
        "O",
        "P",
        "Q",
        "R",
        "S",
        "T",
        "U",
        "V",
        "W",
        "X",
        "Y",
        "Z",
        "0",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
      ],
    },
  },
  valeria: {
    key: "valeria",
    name: "Valeria Lotz",
    sheetId: "1tD0qUBePV0-UPSKwXmf9fNDHEO8u4dOtfDyvKerxVvc",
    sheetGid: "2117152575",
    catalogSheetGid: "2117152575",
    catalogMode: "categorized-price-list",
    categoryHome: true,
    summaryMode: "value",
    hideEmptySummarySections: true,
    sendMode: "form-post-email",
    emailTo: "mymfibrofacil@gmail.com,mymfibrofacil.web@gmail.com",
    emailSubjectPrefix: "Valeria Lotz",
    sendEndpoint: "https://script.google.com/macros/s/AKfycbwlEwt2SvBLacxP1hTl8RhjgBOCuo_aebePiPXA8RdcLOpZfgLFaFOTq0GxIjaO-RJxig/exec",
    logoPath: "Logo.png",
    ui: {
      title: "Pedidos Valeria Lotz",
      searchPlaceholder: "Buscar productos o categorías...",
      sendButtonLabel: "Enviar Pedido por Mail",
      detailTitle: "Detalle del pedido",
    },
    thicknessMeta: {},
  },
  alan_alfonsin: {
    key: "alan_alfonsin",
    name: "Alan Alfonsín",
    sheetId: "1tD0qUBePV0-UPSKwXmf9fNDHEO8u4dOtfDyvKerxVvc",
    sheetGid: "1372255980",
    catalogSheetGid: "1372255980",
    catalogMode: "categorized-price-list",
    categoryHome: false,
    summaryMode: "value",
    hideEmptySummarySections: true,
    sendMode: "whatsapp-and-form-post-email",
    sendXubioOrder: false,
    emailTo: "mymfibrofacil@gmail.com,mymfibrofacil.web@gmail.com",
    emailSubjectPrefix: "Pedido Alan Alfonsín",
    sendEndpoint: "https://script.google.com/macros/s/AKfycbwlEwt2SvBLacxP1hTl8RhjgBOCuo_aebePiPXA8RdcLOpZfgLFaFOTq0GxIjaO-RJxig/exec",
    logoPath: "Logo.png",
    ui: {
      title: "Pedidos Alan Alfonsín",
      searchPlaceholder: "Buscar productos o categorías...",
      sendButtonLabel: "Enviar pedido por mail",
      detailTitle: "Detalle del pedido",
    },
    thicknessMeta: {},
    sectionLabels: {
      "section-mdf-3mm-y-5mm": "Categorías",
    },
  },
};
